name: Install OpenFOAM-8 on ubuntu
description: Install OpenFOAM-8 on ubuntu for github actions.
author: Ondrej Winter

runs:
  using: 'composite'
  steps:
  - run: |
      echo "AAA0"
      sudo sh -c "wget --no-check-certificate -O - https://dl.openfoam.org/gpg.key | apt-key add -" > /dev/null
      echo "AAA1"
      sudo add-apt-repository http://dl.openfoam.org/ubuntu > /dev/null
      echo "AAA2"
      sudo apt-get update > /dev/null
      echo "AAA3"
      sudo apt-get -y install openfoam8 > /dev/null
      echo "AAA4"
      source $FOAM8_BASHRC
      echo "AAA5"
      mkdir -p $FOAM_RUN
      echo "AAA6"
      cp -r $FOAM_TUTORIALS $FOAM_RUN
    shell: bash
    env:
      FOAM8_BASHRC: "/opt/openfoam8/etc/bashrc"
