name: Install OpenFOAM-8 on ubuntu
description: Install OpenFOAM-8 on ubuntu for github actions.
author: Ondrej Winter

runs:
  using: 'composite'
  steps:
    - name: Installation
      run: install
      env:
        FOAM8_BASHRC: /opt/openfoam8/etc/bashrc
      shell: bash
